# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr: none

pool:
  vmImage: 'ubuntu-latest'

name: $(BaseVersion)-b$(BuildID)

steps:
- task: file-creator@5
  displayName: create template.version.nuspec
  inputs:
    filepath: 'template/template.version.nuspec'
    filecontent: |
      <?xml version="1.0" encoding="utf-8"?>
      <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd" xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
        <metadata>
          <version xdt:Transform="Replace">$(Build.BuildNumber)</version>    
        </metadata>
      </package>

- task: FileTransform@2
  displayName: add version to .cynosura.json
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    xmlTransformationRules: '-transform **\template.version.nuspec -xml **\template.nuspec'
    jsonTargetFiles: 'src/.cynosura.json'

- task: PowerShell@2
  displayName: run prepare content
  inputs:
    filePath: 'template/prepare-content.ps1'
    workingDirectory: 'template/'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.4.x'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'template/template.nuspec'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: nuget push to github
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Github Package Registry'