trigger: 
  tags:
    include:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-22.04'

steps:

- task: PowerShell@2
  displayName: run prepare content
  inputs:
    filePath: 'template/prepare-content.ps1'
    workingDirectory: 'template/'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec:

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'pack template/template.nuspec -OutputDirectory $(Build.ArtifactStagingDirectory) -NoDefaultExcludes'

- task: NuGetCommand@2
  displayName: nuget push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'

- task: NuGetCommand@2
  displayName: nuget push to github
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Github Package Registry'