# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr: none

pool:
  vmImage: 'ubuntu-latest'

name: $(BaseVersion)-b$(BuildID)

steps:
- task: FileTransform@2
  displayName: add version to .cynosura.json
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    xmlTransformationRules: 
    jsonTargetFiles: 'src/.cynosura.json'

- task: PowerShell@2
  displayName: run prepare content
  inputs:
    filePath: 'template/prepare-content.ps1'
    workingDirectory: 'template/'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'template'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'template/template.nuspec'
    versioningScheme: 'byBuildNumber'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: nuget push to github
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Github Package Registry'