version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Cynosura.Template.Web/Dockerfile
    depends_on:
      - db
  webng:
    build:
      context: Cynosura.Template.Web.Ng
  worker:
    build:
      context: .
      dockerfile: Cynosura.Template.Worker/Dockerfile
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
  mq:
    image: rabbitmq:3.8-management
    hostname: "mq"